## Basic Tensor Operation in Tensorflow

### What is Tensor? 
- A Tensor is an N-dimensional array of data.
<p align="center">
    <img src="Tensor.png"  width="600" height="300">
p>


In [2]:
# import necessary modules

# the command below ignors warnings
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

# physical_devices = tf.config.list_physical_devices('GPU') 
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

### Initialization of Tensors

In [16]:
x = tf.constant(5)
y = tf.constant(5.0)
z = tf.constant(5, shape=(1,))
m = tf.constant(5, shape=(1, 1), dtype=tf.float32)
print(x)
print("Tensor Dimension:", x.ndim)
print("Tensor Shape:", x.shape)
print("Tensor Type:", x.dtype) 

print("---------------------------------")
print("Tensor Dimension:", y.ndim)
print("Tensor Shape:", y.shape)
print("Tensor Type:", y.dtype) 

print("---------------------------------")
print("Tensor Dimension:", z.ndim)
print("Tensor Shape:", z.shape)
print("Tensor Type:", z.dtype) 

print("---------------------------------")
print("Tensor Dimension:", m.ndim)
print("Tensor Shape:", m.shape)
print("Tensor Type:", m.dtype) 


tf.Tensor(5, shape=(), dtype=int32)
Tensor Dimension: 0
Tensor Shape: ()
Tensor Type: <dtype: 'int32'>
---------------------------------
Tensor Dimension: 0
Tensor Shape: ()
Tensor Type: <dtype: 'float32'>
---------------------------------
Tensor Dimension: 1
Tensor Shape: (1,)
Tensor Type: <dtype: 'int32'>
---------------------------------
Tensor Dimension: 2
Tensor Shape: (1, 1)
Tensor Type: <dtype: 'float32'>


In [17]:
a = tf.constant([[1, 2, 3, 4], [11, 22, 33, 44]])
print(a)

tf.Tensor(
[[ 1  2  3  4]
 [11 22 33 44]], shape=(2, 4), dtype=int32) (2, 4)


In [15]:
x = tf.ones(shape=(3, 3), dtype=tf.float32)
print(x)
print("Tensor Dimension:", x.ndim)
print("Tensor Shape:", x.shape)
print("Tensor Type:", x.dtype) 

print("---------------------------------")
y = tf.zeros(shape=(2, 1), dtype=tf.int32)
print(y)
print("Tensor Dimension:", y.ndim)
print("Tensor Shape:", y.shape)
print("Tensor Type:", y.dtype) 

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
Tensor Dimension: 2
Tensor Shape: (3, 3)
Tensor Type: <dtype: 'float32'>
---------------------------------
tf.Tensor(
[[0]
 [0]], shape=(2, 1), dtype=int32)
Tensor Dimension: 2
Tensor Shape: (2, 1)
Tensor Type: <dtype: 'int32'>


In [17]:
# I for Identity matrix(eye)
x = tf.eye(2)
y = tf.eye(2, 4)
print(x)
print("---------------------------------")
print(y)

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
---------------------------------
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]], shape=(2, 4), dtype=float32)


In [18]:
# create a matrix of Standard Normal Distribution
x = tf.random.normal(shape=(3, 3),  mean=0, stddev=1)
print(x)


tf.Tensor(
[[-0.29693615 -1.322395   -0.3649799 ]
 [-1.9506166  -0.9418601  -0.6727223 ]
 [ 0.34973788 -1.907273    1.2210419 ]], shape=(3, 3), dtype=float32)


In [19]:
# create a matrix of Uniform Distribution: [minval, maxval)
x = tf.random.uniform(shape=(1, 3), minval=0, maxval=2)
print(x)

tf.Tensor([[0.23287249 0.00309634 1.2859795 ]], shape=(1, 3), dtype=float32)


In [20]:
x = tf.range(8)
y = tf.range(start=3, limit=20, delta=5)
print(x)
print("---------------------------------")
print(y)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
---------------------------------
tf.Tensor([ 3  8 13 18], shape=(4,), dtype=int32)


In [33]:
# convert between different types 
# like: tf.float(16, 32, 64), tf.int(8, 16, 32, 64), tf.bool
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7.], shape=(8,), dtype=float32)


### Mathematical Operations 

In [21]:
# elemenwise add and subtract
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)   # or z = x + y
print(z)
print("---------------------------------")
z = tf.subtract(x, y)   # or z = x - y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
---------------------------------
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [22]:
# elementwise multiplication and division
z = tf.multiply(x, y)   # or z = x * y
print(z)
print("---------------------------------")
z = tf.divide(x, y)     # or z = x / y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
---------------------------------
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [42]:
# dot product(elementwise)
z = tf.tensordot(x, y, axes=1)   # or tf.reduce_sum(x*y, axis=0)
print(z)


tf.Tensor(46, shape=(), dtype=int32)


In [43]:
# Elementwis Exponention
z = x**2
print(z)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [52]:
# Matrix Multiplication

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)
# or 
z = x @ y
print(z)

tf.Tensor(
[[-1.7686853   2.958541   -0.6189273  -1.4002525 ]
 [-0.9542395   2.071267   -0.59745026 -1.1870003 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.7686853   2.958541   -0.6189273  -1.4002525 ]
 [-0.9542395   2.071267   -0.59745026 -1.1870003 ]], shape=(2, 4), dtype=float32)


### Indexing of Tensors

In [65]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2]) # skip with delta=2
print(x[::-2])

# gather specific index form tensor
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

print('-------------------------')
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0])
print(x[0, :])
print(x[0][:])  

print('-------------------------')
print(x[1:3, :])   

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 1 2 1], shape=(4,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
-------------------------
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
-------------------------
tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)


### Reshaping of Tensors

In [26]:
x = tf.range(9)
x = tf.reshape(x, (3, 3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [28]:
# Transpose 
print(x)

print('-------------------------')
x1 = tf.transpose(x)
print(x1)

print('-------------------------')
x2 = tf.transpose(x, perm=[1, 0]) # per: permutation
print(x2)
# The returned tensor's dimension i will correspond to 
# the input dimension perm[i]. If perm is not given, it
# is set to (n-1...0), where n is the rank of the input tensor. 

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
-------------------------
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
-------------------------
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
